### ISSUE TITLE
Tracking Issue for Features needed for 1.0

### ISSUE THREAD

**Issue by Vadoola** [Vadoola/Tomotroid#66]
It's probably time I create a tracking Issue so I can more easily see what features have not yet been implemented.

- [ ] Reset Timers to Defaults, "button" is there, but no functionality: Tracked in Issue #62 
- [ ] Always On Top
- [ ] Deactivate Always On Top during breaks
- [ ] Auto Start Work Timer: Right now the timer always auto starts regardless of this setting, need to add in support for it, so it either starts, or waits to be manually started
- [ ] Auto Start Break Timer: Right now the timer always auto starts regardless of this setting, need to add in support for it, so it either starts, or waits to be manually started
- [ ] Get Sound working: Tick Sounds, Tick Sounds during Break, Notification Sounds
- [ ] Notifications: Issue #2 
- [ ] Finish Adding Tray Support: Issue #1 
- [ ] Global Hot Keys: Issue #29 
- [ ] Proper App Icons on Windows, Linux, Mac
- [ ] Create Installers
